# Generated by Django 2.1.7 on 2019-05-14 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('inout', models.CharField(choices=[('in', '収入'), ('out', '支出')], max_length=100)),
                ('name', models.CharField(max_length=20, verbose_name='項目名')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999999999)])),
            ],
        ),
    ]
