# Generated by Django 2.2.1 on 2019-05-18 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='日付')),
                ('category', models.CharField(choices=[('食費', '食費'), ('日用雑貨', '日用雑貨'), ('交通', '交通'), ('通信', '通信'), ('水道・光熱', '水道・光熱'), ('住まい', '住まい'), ('交際費', '交際費'), ('エンタメ', 'エンタメ'), ('教育・教養', '教育・教養'), ('税金', '税金'), ('その他', 'その他')], default='食費', max_length=100)),
                ('inout', models.CharField(choices=[('in', '収入'), ('out', '支出')], max_length=100)),
                ('name', models.CharField(max_length=20, verbose_name='項目名')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999999999)])),
            ],
        ),
    ]
