# Generated by Django 2.2.1 on 2019-05-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190514_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('食費', '食費'), ('日用雑貨', '日用雑貨'), ('交通', '交通'), ('通信', '通信'), ('水道・光熱', '水道・光熱'), ('住まい', '住まい'), ('交際費', '交際費'), ('エンタメ', 'エンタメ'), ('教育・教養', '教育・教養'), ('税金', '税金'), ('その他', 'その他')], default='食費', max_length=100),
        ),
    ]
